env:
  variables:
    VITE_API_BASE_URL: FIXME_VITE_API_BASE_URL
    VITE_STRIPE_PRICE_ID_PRO_MONTHLY: FIXME_VITE_STRIPE_PRICE_ID_PRO_MONTHLY
    VITE_STRIPE_PRICE_ID_STARTER_MONTHLY: FIXME_VITE_STRIPE_PRICE_ID_STARTER_MONTHLY
    VITE_STRIPE_PUBLISH_KEY: FIXME_VITE_STRIPE_PUBLISH_KEY
