---
kind: pipeline
type: docker
name: python

environment:
  LAST_COMMIT_HASH: "$${DRONE_COMMIT_SHA::7}"

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - printf "python-%s" $(git describe --tags --always --dirty) > .tags

  - name: build Python image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}:$(cat .tags)" -f docker/python.dockerfile .
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
    - master
    - feature/*
  event:
    - push
