# https://ahmet.im/blog/kubernetes-network-policy/
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" $ | indent 4 }}
spec:
  podSelector:
    matchLabels: {}
  ingress:
    - {}