name: Docker Image CI

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Python Docker image
        run: docker build . --file docker/python.dockerfile --tag learn:python
